site_name: "Documentação Auth"
theme:
  name: material

nav:
  - Início: index.md
  - Fluxo de Autenticação: fluxo-autenticacao.md
  - Arquitetura: arquitetura.md
  - Entidades: entidades.md
  - Endpoints: endpoints.md
  - Segurança: seguranca.md
  - Setup: setup.md
